package genframework

import (
	"bytes"
	"fmt"
)

// genDataSource emits a read-only data source for the noun. It reuses the
// resource's model (<noun>Model) and read<Noun> mapper: the user supplies a
// lookup key (identity, or name when present) and every attribute is returned
// Computed.
func genDataSource(cfg Config, r Resource) ([]byte, error) {
	var b bytes.Buffer
	recv := lowerFirst(r.Noun) + "DataSource"
	model := r.model()
	svc := "d.client." + cfg.ClientField
	pkg := cfg.BindingsPkg

	fmt.Fprintf(&b, "// Code generated by gen-tf; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", cfg.Package)

	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t%q\n\n", "context")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/datasource")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/datasource/schema")
	if r.hasSet() || r.DataSourceOnly {
		fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/types")
	}
	fmt.Fprintf(&b, "\n\t%q\n", "github.com/terraprovider/go-msadmin/consistency")
	fmt.Fprintf(&b, "\t%q\n", cfg.BindingsImport)
	fmt.Fprintf(&b, "\t%q\n", cfg.ClientsImport)
	fmt.Fprintf(&b, "\t%q\n", "github.com/terraprovider/tf-msadmin/resourcex")
	fmt.Fprintf(&b, ")\n\n")

	fmt.Fprintf(&b, "var (\n")
	fmt.Fprintf(&b, "\t_ datasource.DataSource = &%s{}\n", recv)
	fmt.Fprintf(&b, "\t_ datasource.DataSourceWithConfigure = &%s{}\n", recv)
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "type %s struct{ client *clients.Client }\n\n", recv)
	fmt.Fprintf(&b, "// New%sDataSource looks up a %s object (%s).\n", r.Noun, r.Noun, r.cmdlet("Get"))
	fmt.Fprintf(&b, "func New%sDataSource() datasource.DataSource { return &%s{} }\n\n", r.Noun, recv)

	fmt.Fprintf(&b, "func (d *%s) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {\n", recv)
	fmt.Fprintf(&b, "\tresp.TypeName = req.ProviderTypeName + %q\n}\n\n", "_"+r.TFName)

	// Schema: id computed; identity (and name, if present) optional lookup keys;
	// everything else computed.
	fmt.Fprintf(&b, "func (d *%s) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {\n", recv)
	fmt.Fprintf(&b, "\tresp.Schema = schema.Schema{\n")
	fmt.Fprintf(&b, "\t\tDescription: %q,\n", "Look up an existing "+r.Noun+" object. Set identity"+nameHint(r)+" to select it.")
	fmt.Fprintf(&b, "\t\tAttributes: map[string]schema.Attribute{\n")
	fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n", "id", "Object identifier (GUID).")
	fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Optional: true, Computed: true, Description: %q},\n", "identity", "Identity used to look up the object.")
	if r.RawJSON {
		fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n", "name", "Name of the object.")
		fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n", "display_name", "Display name of the object.")
		fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n", "json", "The full object encoded as JSON; decode with jsondecode().")
	} else {
		for _, a := range r.Attributes {
			optional := a.Field == "Name"
			fmt.Fprintf(&b, "\t\t\t%q: %s,\n", a.TFName, dsSchemaAttr(a, optional))
		}
		if r.Members != nil {
			fmt.Fprintf(&b, "\t\t\t%q: schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: %q},\n", r.Members.TFName, r.Members.Description)
		}
	}
	fmt.Fprintf(&b, "\t\t},\n\t}\n}\n\n")

	fmt.Fprintf(&b, "func (d *%s) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {\n", recv)
	fmt.Fprintf(&b, "\tif req.ProviderData == nil {\n\t\treturn\n\t}\n")
	fmt.Fprintf(&b, "\td.client = req.ProviderData.(*clients.Client)\n}\n\n")

	// Read.
	fmt.Fprintf(&b, "func (d *%s) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {\n", recv)
	fmt.Fprintf(&b, "\tvar data %s\n", model)
	fmt.Fprintf(&b, "\tresp.Diagnostics.Append(req.Config.Get(ctx, &data)...)\n")
	fmt.Fprintf(&b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	if r.hasName() {
		fmt.Fprintf(&b, "\tidentity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())\n")
	} else {
		fmt.Fprintf(&b, "\tidentity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())\n")
	}
	// A singleton read takes no key (Read.IdentityField == ""); only require an
	// identity when the read actually uses one to select the object.
	if r.Read.IdentityField != "" {
		fmt.Fprintf(&b, "\tif identity == \"\" {\n\t\tresp.Diagnostics.AddError(%q, %q)\n\t\treturn\n\t}\n", "Missing lookup key", "set identity"+nameHint(r)+" to select the object")
	}
	fmt.Fprintf(&b, "\tget := func(ctx context.Context) (map[string]any, bool, error) {\n")
	if r.Read.IdentityField != "" {
		fmt.Fprintf(&b, "\t\tres, gerr := %s.%s(ctx, %s.%s{%s: identity})\n", svc, r.Read.Method, pkg, r.Read.Params, r.Read.IdentityField)
	} else {
		fmt.Fprintf(&b, "\t\t_ = identity\n\t\tres, gerr := %s.%s(ctx, %s.%s{})\n", svc, r.Read.Method, pkg, r.Read.Params)
	}
	fmt.Fprintf(&b, "\t\tif gerr != nil {\n\t\t\tif isNotFound(gerr) {\n\t\t\t\treturn nil, false, nil\n\t\t\t}\n\t\t\treturn nil, false, gerr\n\t\t}\n")
	fmt.Fprintf(&b, "\t\to := firstObject(res.Value)\n\t\treturn o, o != nil, nil\n\t}\n")
	fmt.Fprintf(&b, "\tobj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)\n")
	fmt.Fprintf(&b, "\tif err != nil {\n\t\tresp.Diagnostics.AddError(%q, err.Error())\n\t\treturn\n\t}\n", r.cmdlet("Get")+" failed")
	fmt.Fprintf(&b, "\tif !present {\n\t\tresp.Diagnostics.AddError(%q, %q+identity)\n\t\treturn\n\t}\n", r.Noun+" not found", "no "+r.Noun+" object for identity ")
	fmt.Fprintf(&b, "\tread%s(ctx, obj, &data)\n", r.Noun)
	if r.Members != nil {
		fmt.Fprintf(&b, "\tread%sMembers(ctx, %s, identity, &data)\n", r.Noun, svc)
	}
	fmt.Fprintf(&b, "\tresp.Diagnostics.Append(resp.State.Set(ctx, &data)...)\n}\n\n")

	// A standalone (Get-only) data source has no resource file, so it carries
	// its own model + read<Noun>.
	if r.DataSourceOnly {
		fmt.Fprintf(&b, "type %s struct {\n", model)
		fmt.Fprintf(&b, "\tID types.String `tfsdk:\"id\"`\n")
		fmt.Fprintf(&b, "\tIdentity types.String `tfsdk:\"identity\"`\n")
		if r.RawJSON {
			fmt.Fprintf(&b, "\tName types.String `tfsdk:\"name\"`\n")
			fmt.Fprintf(&b, "\tDisplayName types.String `tfsdk:\"display_name\"`\n")
			fmt.Fprintf(&b, "\tJSON types.String `tfsdk:\"json\"`\n")
		} else {
			for _, a := range r.Attributes {
				fmt.Fprintf(&b, "\t%s\n", a.modelField())
			}
		}
		fmt.Fprintf(&b, "}\n\n")
		genReadInto(&b, r, model)
	}

	return gofmt(b.String())
}

func nameHint(r Resource) string {
	if r.hasName() {
		return " or name"
	}
	return ""
}

// dsSchemaAttr renders a data source schema attribute: Computed, plus Optional
// when it is also a lookup key.
func dsSchemaAttr(a Attribute, optional bool) string {
	var b bytes.Buffer
	kind := a.tfType()
	switch a.Type {
	case TypeStringSet:
		b.WriteString("schema.SetAttribute{ElementType: types.StringType, Computed: true, ")
	default:
		fmt.Fprintf(&b, "schema.%sAttribute{Computed: true, ", kind)
	}
	if optional {
		b.WriteString("Optional: true, ")
	}
	if a.Sensitive {
		b.WriteString("Sensitive: true, ")
	}
	fmt.Fprintf(&b, "Description: %q}", a.Description)
	return b.String()
}

// genPluralDataSource emits a "list" data source: it calls Get-<Noun> with no
// key and returns every object as a read-only list of nested objects. It reuses
// the singular's <noun>Model element type and read<Noun> mapper. There is no
// per-object retry (a bulk list, not a single-object eventual-consistency read).
func genPluralDataSource(cfg Config, r Resource) ([]byte, error) {
	var b bytes.Buffer
	recv := r.pluralRecv()
	model := r.pluralModel()
	elem := r.model()
	svc := "d.client." + cfg.ClientField
	pkg := cfg.BindingsPkg
	attr := r.pluralTFName()

	fmt.Fprintf(&b, "// Code generated by gen-tf; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", cfg.Package)

	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t%q\n\n", "context")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/datasource")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/datasource/schema")
	// Always needed: each element's identity is set via types.StringValue below.
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/types")
	fmt.Fprintf(&b, "\n\t%q\n", cfg.BindingsImport)
	fmt.Fprintf(&b, "\t%q\n", cfg.ClientsImport)
	fmt.Fprintf(&b, ")\n\n")

	fmt.Fprintf(&b, "var (\n")
	fmt.Fprintf(&b, "\t_ datasource.DataSource = &%s{}\n", recv)
	fmt.Fprintf(&b, "\t_ datasource.DataSourceWithConfigure = &%s{}\n", recv)
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "type %s struct{ client *clients.Client }\n\n", recv)
	fmt.Fprintf(&b, "// %s lists every %s object (%s).\n", r.pluralCtor(), r.Noun, r.cmdlet("Get"))
	fmt.Fprintf(&b, "func %s() datasource.DataSource { return &%s{} }\n\n", r.pluralCtor(), recv)

	// Model: a single computed list of the singular element model.
	fmt.Fprintf(&b, "type %s struct {\n\tItems []%s `tfsdk:%q`\n}\n\n", model, elem, attr)

	fmt.Fprintf(&b, "func (d *%s) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {\n", recv)
	fmt.Fprintf(&b, "\tresp.TypeName = req.ProviderTypeName + %q\n}\n\n", "_"+attr)

	// Schema: one Computed ListNestedAttribute; every element attribute Computed.
	fmt.Fprintf(&b, "func (d *%s) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {\n", recv)
	fmt.Fprintf(&b, "\tresp.Schema = schema.Schema{\n")
	fmt.Fprintf(&b, "\t\tDescription: %q,\n", "List every "+r.Noun+" object ("+r.cmdlet("Get")+").")
	fmt.Fprintf(&b, "\t\tAttributes: map[string]schema.Attribute{\n")
	fmt.Fprintf(&b, "\t\t\t%q: schema.ListNestedAttribute{Computed: true, Description: %q, NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{\n", attr, "All "+r.Noun+" objects.")
	fmt.Fprintf(&b, "\t\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n", "id", "Object identifier (GUID).")
	fmt.Fprintf(&b, "\t\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n", "identity", "Identity used to target the object.")
	if r.RawJSON {
		fmt.Fprintf(&b, "\t\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n", "name", "Name of the object.")
		fmt.Fprintf(&b, "\t\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n", "display_name", "Display name of the object.")
		fmt.Fprintf(&b, "\t\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n", "json", "The full object encoded as JSON; decode with jsondecode().")
	} else {
		for _, a := range r.Attributes {
			fmt.Fprintf(&b, "\t\t\t\t%q: %s,\n", a.TFName, dsSchemaAttr(a, false))
		}
		if r.Members != nil {
			fmt.Fprintf(&b, "\t\t\t\t%q: schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: %q},\n", r.Members.TFName, r.Members.Description)
		}
	}
	fmt.Fprintf(&b, "\t\t\t}}},\n")
	fmt.Fprintf(&b, "\t\t},\n\t}\n}\n\n")

	fmt.Fprintf(&b, "func (d *%s) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {\n", recv)
	fmt.Fprintf(&b, "\tif req.ProviderData == nil {\n\t\treturn\n\t}\n")
	fmt.Fprintf(&b, "\td.client = req.ProviderData.(*clients.Client)\n}\n\n")

	// Read: list all (Get with no key), map each object via the shared read<Noun>.
	fmt.Fprintf(&b, "func (d *%s) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {\n", recv)
	fmt.Fprintf(&b, "\tres, err := %s.%s(ctx, %s.%s{})\n", svc, r.Read.Method, pkg, r.Read.Params)
	fmt.Fprintf(&b, "\tif err != nil {\n\t\tresp.Diagnostics.AddError(%q, err.Error())\n\t\treturn\n\t}\n", r.cmdlet("Get")+" failed")
	fmt.Fprintf(&b, "\tvar data %s\n", model)
	fmt.Fprintf(&b, "\tfor _, obj := range res.Value {\n")
	fmt.Fprintf(&b, "\t\tvar e %s\n", elem)
	fmt.Fprintf(&b, "\t\tread%s(ctx, obj, &e)\n", r.Noun)
	// read<Noun> preserves a user-supplied identity for the singular resource/data
	// source (and so leaves it unset for IdentityIsName), but a list element has no
	// input identity — populate it from the read-back object here.
	fmt.Fprintf(&b, "\t\te.Identity = types.StringValue(%s)\n", r.identityReadExpr())
	if r.Members != nil {
		fmt.Fprintf(&b, "\t\te.%s = stringSetValue(ctx, nil)\n", r.Members.Field)
	}
	fmt.Fprintf(&b, "\t\tdata.Items = append(data.Items, e)\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tresp.Diagnostics.Append(resp.State.Set(ctx, &data)...)\n}\n")

	return gofmt(b.String())
}
