package genframework

import (
	"bytes"
	"fmt"
)

func genRegistration(cfg Config, resources []Resource) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen-tf; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", cfg.Package)
	fmt.Fprintf(&b, "import (\n\t%q\n\t%q\n)\n\n",
		"github.com/hashicorp/terraform-plugin-framework/datasource",
		"github.com/hashicorp/terraform-plugin-framework/resource")
	fmt.Fprintf(&b, "// generatedResources lists every generated resource constructor.\n")
	fmt.Fprintf(&b, "func generatedResources() []func() resource.Resource {\n")
	fmt.Fprintf(&b, "\treturn []func() resource.Resource{\n")
	for _, r := range resources {
		if r.DataSourceOnly {
			continue
		}
		fmt.Fprintf(&b, "\t\t%s,\n", r.ctor())
	}
	fmt.Fprintf(&b, "\t}\n}\n\n")
	fmt.Fprintf(&b, "// generatedDataSources lists every generated data source constructor.\n")
	fmt.Fprintf(&b, "func generatedDataSources() []func() datasource.DataSource {\n")
	fmt.Fprintf(&b, "\treturn []func() datasource.DataSource{\n")
	for _, r := range resources {
		fmt.Fprintf(&b, "\t\tNew%sDataSource,\n", r.Noun)
		if r.Plural {
			fmt.Fprintf(&b, "\t\t%s,\n", r.pluralCtor())
		}
	}
	fmt.Fprintf(&b, "\t}\n}\n")
	return gofmt(b.String())
}

func genResource(cfg Config, r Resource) ([]byte, error) {
	var b bytes.Buffer
	recv := r.recv()
	model := r.model()
	svc := "r.client." + cfg.ClientField
	pkg := cfg.BindingsPkg

	fmt.Fprintf(&b, "// Code generated by gen-tf; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", cfg.Package)

	// Imports — over-include is not an option (unused imports fail), so include
	// exactly what the body references.
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t%q\n\n", "context")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/diag")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/path")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier")
	if r.hasBoolMod() {
		fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier")
	}
	if r.hasSet() {
		fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier")
	}
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier")
	fmt.Fprintf(&b, "\t%q\n\n", "github.com/hashicorp/terraform-plugin-framework/types")
	fmt.Fprintf(&b, "\t%q\n", "github.com/terraprovider/go-msadmin/consistency")
	fmt.Fprintf(&b, "\t%q\n", cfg.BindingsImport)
	fmt.Fprintf(&b, "\t%q\n", cfg.ClientsImport)
	fmt.Fprintf(&b, "\t%q\n", "github.com/terraprovider/tf-msadmin/reconcile")
	fmt.Fprintf(&b, "\t%q\n", "github.com/terraprovider/tf-msadmin/resourcex")
	fmt.Fprintf(&b, ")\n\n")

	// Interface asserts + type + constructor.
	fmt.Fprintf(&b, "var (\n")
	fmt.Fprintf(&b, "\t_ resource.Resource = &%s{}\n", recv)
	fmt.Fprintf(&b, "\t_ resource.ResourceWithConfigure = &%s{}\n", recv)
	fmt.Fprintf(&b, "\t_ resource.ResourceWithImportState = &%s{}\n", recv)
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "type %s struct{ client *clients.Client }\n\n", recv)
	if r.Config {
		fmt.Fprintf(&b, "// %s manages the %s configuration (%s / %s); it adopts the existing object and is not deleted on destroy.\n",
			r.ctor(), r.Noun, r.cmdlet("Get"), r.cmdlet("Set"))
	} else {
		fmt.Fprintf(&b, "// %s manages the %s object (%s / %s / %s / %s).\n",
			r.ctor(), r.Noun, r.cmdlet("New"), r.cmdlet("Get"), r.cmdlet("Set"), r.cmdlet("Remove"))
	}
	fmt.Fprintf(&b, "func %s() resource.Resource { return &%s{} }\n\n", r.ctor(), recv)

	// Model.
	fmt.Fprintf(&b, "type %s struct {\n", model)
	fmt.Fprintf(&b, "\tID types.String `tfsdk:\"id\"`\n")
	fmt.Fprintf(&b, "\tIdentity types.String `tfsdk:\"identity\"`\n")
	for _, a := range r.Attributes {
		fmt.Fprintf(&b, "\t%s\n", a.modelField())
	}
	if r.Members != nil {
		fmt.Fprintf(&b, "\t%s types.Set `tfsdk:%q`\n", r.Members.Field, r.Members.TFName)
	}
	fmt.Fprintf(&b, "}\n\n")

	// Metadata.
	fmt.Fprintf(&b, "func (r *%s) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {\n", recv)
	fmt.Fprintf(&b, "\tresp.TypeName = req.ProviderTypeName + %q\n}\n\n", "_"+r.TFName)

	// Schema.
	fmt.Fprintf(&b, "func (r *%s) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {\n", recv)
	fmt.Fprintf(&b, "\tresp.Schema = schema.Schema{\n")
	fmt.Fprintf(&b, "\t\tDescription: %q,\n", r.Description)
	fmt.Fprintf(&b, "\t\tAttributes: map[string]schema.Attribute{\n")
	fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},\n",
		"id", "Object identifier (GUID).")
	if r.Config && !r.Singleton {
		fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Required: true, Description: %q, PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},\n",
			"identity", "Identity of the existing object whose configuration is managed.")
	} else if r.IdentityIsName {
		fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Required: true, Description: %q, PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},\n",
			"identity", "Name (Identity) of the object; also the create key. Changing it forces replacement.")
	} else {
		fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n",
			"identity", "Identity used to target the object in cmdlets.")
	}
	for _, a := range r.Attributes {
		fmt.Fprintf(&b, "\t\t\t%q: %s,\n", a.TFName, a.schemaAttr())
	}
	if r.Members != nil {
		fmt.Fprintf(&b, "\t\t\t%q: schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: %q, PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},\n",
			r.Members.TFName, r.Members.Description)
	}
	fmt.Fprintf(&b, "\t\t},\n\t}\n}\n\n")

	// Configure.
	fmt.Fprintf(&b, "func (r *%s) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {\n", recv)
	fmt.Fprintf(&b, "\tif req.ProviderData == nil {\n\t\treturn\n\t}\n")
	fmt.Fprintf(&b, "\tr.client = req.ProviderData.(*clients.Client)\n}\n\n")

	if r.Config {
		genConfigCreate(&b, cfg, r, recv, model, svc, pkg)
	} else {
		genCreate(&b, cfg, r, recv, model, svc, pkg)
	}
	genRead(&b, cfg, r, recv, model)
	genUpdate(&b, cfg, r, recv, model, svc, pkg)
	if r.Config {
		genConfigDelete(&b, r, recv, model)
	} else {
		genDelete(&b, cfg, r, recv, model, svc, pkg)
	}
	genImport(&b, recv)
	genHelpers(&b, cfg, r, recv, model, svc, pkg)

	return gofmt(b.String())
}

func genCreate(b *bytes.Buffer, cfg Config, r Resource, recv, model, svc, pkg string) {
	fmt.Fprintf(b, "func (r *%s) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {\n", recv)
	fmt.Fprintf(b, "\tvar plan %s\n", model)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)\n")
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n\n")
	if r.SparseWrite {
		// Sparse create: send only the fields the operator actually set. Every
		// unconfigured Optional+Computed attribute is unknown here; omitting it
		// avoids force-setting tri-state *bool params to false (which the Teams API
		// rejects with 403 for permission-gated toggles) and matches how the
		// New-Cs* cmdlets behave — they touch only the parameters you pass.
		fmt.Fprintf(b, "\tp := %s.%s{}\n", pkg, r.Create.Params)
		for _, a := range r.Attributes {
			if !a.InCreate {
				continue
			}
			if a.Object {
				fmt.Fprintf(b, "\tif v := plan.%s.ValueString(); v != \"\" {\n\t\tp.%s = v\n\t}\n", a.Field, a.Field)
				continue
			}
			fmt.Fprintf(b, "\tif !plan.%s.IsUnknown() && !plan.%s.IsNull() {\n\t\tp.%s = %s\n\t}\n", a.Field, a.Field, a.Field, a.planValue())
		}
	} else {
		fmt.Fprintf(b, "\tp := %s.%s{\n", pkg, r.Create.Params)
		for _, a := range r.Attributes {
			if a.InCreate && !a.Object {
				fmt.Fprintf(b, "\t\t%s: %s,\n", a.Field, a.planValue())
			}
		}
		fmt.Fprintf(b, "\t}\n")
		// System.Object params are `any` fields: only set when non-empty so "" is
		// not marshalled as a value.
		for _, a := range r.Attributes {
			if a.InCreate && a.Object {
				fmt.Fprintf(b, "\tif v := plan.%s.ValueString(); v != \"\" {\n\t\tp.%s = v\n\t}\n", a.Field, a.Field)
			}
		}
	}
	// IdentityIsName: the create is keyed by the user-chosen identity/name.
	if r.IdentityIsName {
		key := r.Create.IdentityField
		if key == "" {
			key = "Identity"
		}
		fmt.Fprintf(b, "\tp.%s = plan.Identity.ValueString()\n", key)
	}
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tres, err := %s.%s(ctx, p)\n", svc, r.Create.Method)
	fmt.Fprintf(b, "\tif err != nil {\n\t\tresp.Diagnostics.AddError(%q, err.Error())\n\t\treturn\n\t}\n", r.cmdlet("New")+" failed")
	fmt.Fprintf(b, "\tobj := firstObject(res.Value)\n")
	fmt.Fprintf(b, "\tcfg := plan\n")
	// Read-back target: for IdentityIsName the New cmdlet may not echo the created
	// object (the Teams policy API stores it but returns an empty body), so refresh
	// by the user-chosen identity rather than a field of the (possibly nil)
	// response.
	if r.IdentityIsName {
		fmt.Fprintf(b, "\tident := plan.Identity.ValueString()\n")
	} else {
		fmt.Fprintf(b, "\tident := %s\n", r.identityReadExpr())
	}
	fmt.Fprintf(b, "\tif !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {\n")
	fmt.Fprintf(b, "\t\tif resp.Diagnostics.HasError() {\n\t\t\treturn\n\t\t}\n")
	// The object couldn't be read back; fall back to the create response, or fail
	// if the API returned neither.
	fmt.Fprintf(b, "\t\tif obj == nil {\n\t\t\tresp.Diagnostics.AddError(%q, %q)\n\t\t\treturn\n\t\t}\n", r.cmdlet("New")+" returned no object", "the cmdlet did not return the created object and it could not be read back")
	fmt.Fprintf(b, "\t\tread%s(ctx, obj, &plan)\n\t}\n", r.Noun)
	if mc := r.Members; mc != nil {
		fmt.Fprintf(b, "\tif mem := toStringSlice(ctx, cfg.%s, &resp.Diagnostics); len(mem) > 0 {\n", mc.Field)
		fmt.Fprintf(b, "\t\tif merr := resourcex.RetryWrite(ctx, consistency.Config{}, func(ctx context.Context) error {\n")
		fmt.Fprintf(b, "\t\t\t_, e := %s.%s(ctx, %s.%s{%s: ident, %s: mem})\n\t\t\treturn e\n\t\t}, isNotFound); merr != nil {\n", svc, mc.UpdateMethod, pkg, mc.UpdateParams, mc.IdentityField, mc.MembersField)
		fmt.Fprintf(b, "\t\t\tresp.Diagnostics.AddError(%q, merr.Error())\n\t\t\treturn\n\t\t}\n", "Update-"+r.Noun+"Member failed")
		fmt.Fprintf(b, "\t\tread%sMembers(ctx, %s, ident, &plan)\n\t}\n", r.Noun, svc)
	}
	fmt.Fprintf(b, "\tr.reconcileState(&cfg, &plan)\n")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)\n}\n\n")
}

// genConfigCreate emits Create for a Get+Set config resource: it adopts the
// existing config by applying Set with the configured settings, then reads.
func genConfigCreate(b *bytes.Buffer, cfg Config, r Resource, recv, model, svc, pkg string) {
	fmt.Fprintf(b, "func (r *%s) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {\n", recv)
	fmt.Fprintf(b, "\tvar plan %s\n", model)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)\n")
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tsp := %s.%s{}\n", pkg, r.Update.Params)
	if r.Update.IdentityField != "" {
		fmt.Fprintf(b, "\tsp.%s = plan.Identity.ValueString()\n", r.Update.IdentityField)
	}
	for _, a := range r.Attributes {
		if !a.InUpdate {
			continue
		}
		switch {
		case a.Object:
			fmt.Fprintf(b, "\tif v := plan.%s.ValueString(); v != \"\" {\n\t\tsp.%s = v\n\t}\n", a.Field, a.Field)
		case r.SparseWrite:
			// Adopt-create with no prior state: send only configured fields (omit
			// the unknown Optional+Computed ones) so we don't force-set settings.
			fmt.Fprintf(b, "\tif !plan.%s.IsUnknown() && !plan.%s.IsNull() {\n\t\tsp.%s = %s\n\t}\n", a.Field, a.Field, a.Field, a.planValue())
		default:
			fmt.Fprintf(b, "\tsp.%s = %s\n", a.Field, a.planValue())
		}
	}
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tif _, err := %s.%s(ctx, sp); err != nil {\n\t\tresp.Diagnostics.AddError(%q, err.Error())\n\t\treturn\n\t}\n", svc, r.Update.Method, r.cmdlet("Set")+" failed")
	fmt.Fprintf(b, "\tcfg := plan\n")
	if r.Singleton {
		fmt.Fprintf(b, "\tidentity := \"\"\n")
	} else {
		fmt.Fprintf(b, "\tidentity := plan.Identity.ValueString()\n")
	}
	fmt.Fprintf(b, "\tr.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)\n")
	fmt.Fprintf(b, "\tr.reconcileState(&cfg, &plan)\n")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)\n}\n\n")
}

// genReadInto emits the read<Noun> free function that maps a read-back object
// into the model; shared by the resource, the data source and the standalone
// (Get-only) data source.
func genReadInto(b *bytes.Buffer, r Resource, model string) {
	fmt.Fprintf(b, "func read%s(ctx context.Context, obj map[string]any, m *%s) {\n", r.Noun, model)
	if r.RawJSON {
		fmt.Fprintf(b, "\tm.ID = types.StringValue(firstNonEmptyStr(getString(obj, %q), getString(obj, %q), getString(obj, %q)))\n", "Guid", "Id", "Identity")
		fmt.Fprintf(b, "\tm.Identity = types.StringValue(firstNonEmptyStr(getString(obj, %q), getString(obj, %q)))\n", "Identity", "Name")
		fmt.Fprintf(b, "\tm.Name = types.StringValue(getString(obj, %q))\n", "Name")
		fmt.Fprintf(b, "\tm.DisplayName = types.StringValue(getString(obj, %q))\n", "DisplayName")
		fmt.Fprintf(b, "\tm.JSON = types.StringValue(toJSON(obj))\n")
		fmt.Fprintf(b, "\t_ = ctx\n}\n\n")
		return
	}
	fmt.Fprintf(b, "\tm.ID = types.StringValue(firstNonEmptyStr(getString(obj, %q), getString(obj, %q), getString(obj, %q)))\n", "Guid", "Id", "Identity")
	// Identity is a user-supplied key here and must not be overwritten by a
	// (possibly differently-formatted) read-back value:
	//   - per-object config: identity is a required input;
	//   - IdentityIsName: the read-back carries the scoped form (e.g. "Tag:X")
	//     while the operator configured the bare name "X" — overwriting it would
	//     churn the plan and fail the Required-attribute consistency check.
	if !(r.Config && !r.Singleton) && !r.IdentityIsName {
		fmt.Fprintf(b, "\tm.Identity = types.StringValue(%s)\n", r.identityReadExpr())
	}
	for _, a := range r.Attributes {
		fmt.Fprintf(b, "\t%s\n", a.readAssign())
	}
	fmt.Fprintf(b, "\t_ = ctx\n}\n\n")
}

// genConfigDelete emits a no-op Delete for a config resource: the config cannot
// be deleted, so it is dropped from state with a warning.
func genConfigDelete(b *bytes.Buffer, r Resource, recv, model string) {
	fmt.Fprintf(b, "func (r *%s) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {\n", recv)
	fmt.Fprintf(b, "\tresp.Diagnostics.AddWarning(%q, %q)\n}\n\n",
		r.Noun+" configuration not deleted",
		"This resource manages an existing "+r.Noun+" configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func genRead(b *bytes.Buffer, cfg Config, r Resource, recv, model string) {
	fmt.Fprintf(b, "func (r *%s) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {\n", recv)
	fmt.Fprintf(b, "\tvar state %s\n", model)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.State.Get(ctx, &state)...)\n")
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tif !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {\n")
	fmt.Fprintf(b, "\t\tif !resp.Diagnostics.HasError() {\n\t\t\tresp.State.RemoveResource(ctx)\n\t\t}\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.Set(ctx, &state)...)\n}\n\n")
}

func genUpdate(b *bytes.Buffer, cfg Config, r Resource, recv, model, svc, pkg string) {
	fmt.Fprintf(b, "func (r *%s) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {\n", recv)
	fmt.Fprintf(b, "\tvar plan, state %s\n", model)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)\n")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.State.Get(ctx, &state)...)\n")
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tid := r.identityOf(state)\n")
	fmt.Fprintf(b, "\tsp := %s.%s{}\n", pkg, r.Update.Params)
	if r.Update.IdentityField != "" {
		fmt.Fprintf(b, "\tsp.%s = id\n", r.Update.IdentityField)
	}
	for _, a := range r.Attributes {
		if !a.InUpdate {
			continue
		}
		switch {
		case a.Object:
			fmt.Fprintf(b, "\tif v := plan.%s.ValueString(); v != \"\" {\n\t\tsp.%s = v\n\t}\n", a.Field, a.Field)
		case r.SparseWrite:
			// Sparse update: send only fields that changed, so we don't re-set
			// unchanged (and possibly permission-gated) settings on every apply —
			// matching Set-Cs*, which touches only the parameters you pass.
			fmt.Fprintf(b, "\tif !plan.%s.Equal(state.%s) {\n\t\tsp.%s = %s\n\t}\n", a.Field, a.Field, a.Field, a.planValue())
		default:
			fmt.Fprintf(b, "\tsp.%s = %s\n", a.Field, a.planValue())
		}
	}
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tif _, err := %s.%s(ctx, sp); err != nil {\n\t\tresp.Diagnostics.AddError(%q, err.Error())\n\t\treturn\n\t}\n", svc, r.Update.Method, r.cmdlet("Set")+" failed")
	fmt.Fprintf(b, "\tcfg := plan\n")
	// reflected predicate over string attributes that were updated.
	fmt.Fprintf(b, "\treflected := reconcile.ReflectsFields(map[string]types.String{\n")
	for _, a := range r.Attributes {
		if a.InUpdate && a.Type == TypeString {
			fmt.Fprintf(b, "\t\t%q: cfg.%s,\n", a.APIName, a.Field)
		}
	}
	fmt.Fprintf(b, "\t}, getString)\n")
	fmt.Fprintf(b, "\tr.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)\n")
	if mc := r.Members; mc != nil {
		fmt.Fprintf(b, "\tif !plan.%s.Equal(state.%s) {\n", mc.Field, mc.Field)
		fmt.Fprintf(b, "\t\tmem := toStringSlice(ctx, plan.%s, &resp.Diagnostics)\n", mc.Field)
		fmt.Fprintf(b, "\t\tif merr := resourcex.RetryWrite(ctx, consistency.Config{}, func(ctx context.Context) error {\n")
		fmt.Fprintf(b, "\t\t\t_, e := %s.%s(ctx, %s.%s{%s: id, %s: mem})\n\t\t\treturn e\n\t\t}, isNotFound); merr != nil {\n", svc, mc.UpdateMethod, pkg, mc.UpdateParams, mc.IdentityField, mc.MembersField)
		fmt.Fprintf(b, "\t\t\tresp.Diagnostics.AddError(%q, merr.Error())\n\t\t\treturn\n\t\t}\n", "Update-"+r.Noun+"Member failed")
		fmt.Fprintf(b, "\t\tread%sMembers(ctx, %s, id, &plan)\n\t}\n", r.Noun, svc)
	}
	fmt.Fprintf(b, "\tr.reconcileState(&cfg, &plan)\n")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)\n}\n\n")
}

func genDelete(b *bytes.Buffer, cfg Config, r Resource, recv, model, svc, pkg string) {
	fmt.Fprintf(b, "func (r *%s) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {\n", recv)
	fmt.Fprintf(b, "\tvar state %s\n", model)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.State.Get(ctx, &state)...)\n")
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tif _, err := %s.%s(ctx, %s.%s{%s: r.identityOf(state)}); err != nil {\n", svc, r.Delete.Method, pkg, r.Delete.Params, r.Delete.IdentityField)
	fmt.Fprintf(b, "\t\tif !isNotFound(err) {\n\t\t\tresp.Diagnostics.AddError(%q, err.Error())\n\t\t}\n\t}\n}\n\n", r.cmdlet("Remove")+" failed")
}

func genImport(b *bytes.Buffer, recv string) {
	fmt.Fprintf(b, "func (r *%s) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {\n", recv)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root(%q), req.ID)...)\n", "id")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root(%q), req.ID)...)\n}\n\n", "identity")
}

func genHelpers(b *bytes.Buffer, cfg Config, r Resource, recv, model, svc, pkg string) {
	// identityOf. Returns string (never a non-string): the identity is always a
	// user-facing key (name/GUID/DN). Threading it as string — not any — lets the
	// generated read/delete calls target params typed as a concrete string (e.g.
	// -UserId) as well as the usual System.Object -Identity params.
	fmt.Fprintf(b, "func (r *%s) identityOf(m %s) string {\n", recv, model)
	fmt.Fprintf(b, "\tif v := m.Identity.ValueString(); v != \"\" {\n\t\treturn v\n\t}\n")
	fmt.Fprintf(b, "\tif v := m.ID.ValueString(); v != \"\" {\n\t\treturn v\n\t}\n")
	if r.hasName() {
		fmt.Fprintf(b, "\treturn m.Name.ValueString()\n")
	} else {
		fmt.Fprintf(b, "\treturn \"\"\n")
	}
	fmt.Fprintf(b, "}\n\n")

	// refresh
	fmt.Fprintf(b, "func (r *%s) refresh(ctx context.Context, identity string, m *%s, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {\n", recv, model)
	fmt.Fprintf(b, "\tget := func(ctx context.Context) (map[string]any, bool, error) {\n")
	if r.Read.IdentityField != "" {
		fmt.Fprintf(b, "\t\tres, gerr := %s.%s(ctx, %s.%s{%s: identity})\n", svc, r.Read.Method, pkg, r.Read.Params, r.Read.IdentityField)
	} else {
		fmt.Fprintf(b, "\t\t_ = identity\n\t\tres, gerr := %s.%s(ctx, %s.%s{})\n", svc, r.Read.Method, pkg, r.Read.Params)
	}
	fmt.Fprintf(b, "\t\tif gerr != nil {\n\t\t\tif isNotFound(gerr) {\n\t\t\t\treturn nil, false, nil\n\t\t\t}\n\t\t\treturn nil, false, gerr\n\t\t}\n")
	fmt.Fprintf(b, "\t\to := firstObject(res.Value)\n\t\treturn o, o != nil, nil\n\t}\n")
	fmt.Fprintf(b, "\tobj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\tdiags.AddError(%q, err.Error())\n\t\treturn false\n\t}\n", r.cmdlet("Get")+" failed")
	fmt.Fprintf(b, "\tif !present {\n\t\treturn false\n\t}\n")
	fmt.Fprintf(b, "\tread%s(ctx, obj, m)\n", r.Noun)
	if r.Members != nil {
		fmt.Fprintf(b, "\tread%sMembers(ctx, %s, identity, m)\n", r.Noun, svc)
	}
	fmt.Fprintf(b, "\treturn true\n}\n\n")

	genReadInto(b, r, model)

	// reconcileState
	fmt.Fprintf(b, "func (r *%s) reconcileState(cfg, read *%s) {\n", recv, model)
	for _, a := range r.Attributes {
		fmt.Fprintf(b, "\tread.%s = reconcile.%s(cfg.%s, read.%s)\n", a.Field, a.keepFn(), a.Field, a.Field)
	}
	if r.Members != nil {
		fmt.Fprintf(b, "\tread.%s = reconcile.KeepSet(cfg.%s, read.%s)\n", r.Members.Field, r.Members.Field, r.Members.Field)
	}
	fmt.Fprintf(b, "}\n")

	// read<Noun>Members reads the members sub-collection (needs the client, so it
	// is separate from the shared read<Noun>). The member cmdlets can hit a
	// different backend/DC than the create, so the read retries not-found until
	// the object is visible (rides out cross-DC AD-replication lag). Best-effort:
	// if it never becomes visible it leaves an unset attribute empty rather than
	// failing the read.
	if mc := r.Members; mc != nil {
		fmt.Fprintf(b, "\nfunc read%sMembers(ctx context.Context, svc *%s.Service, identity string, m *%s) {\n", r.Noun, pkg, model)
		fmt.Fprintf(b, "\tvals, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, func(ctx context.Context) ([]map[string]any, bool, error) {\n")
		fmt.Fprintf(b, "\t\tres, gerr := svc.%s(ctx, %s.%s{%s: identity})\n", mc.ReadMethod, pkg, mc.ReadParams, mc.IdentityField)
		fmt.Fprintf(b, "\t\tif gerr != nil {\n\t\t\tif isNotFound(gerr) {\n\t\t\t\treturn nil, false, nil\n\t\t\t}\n\t\t\treturn nil, false, gerr\n\t\t}\n")
		fmt.Fprintf(b, "\t\treturn res.Value, true, nil\n\t}, nil)\n")
		fmt.Fprintf(b, "\tif err != nil || !present {\n\t\tif m.%s.IsNull() || m.%s.IsUnknown() {\n\t\t\tm.%s = stringSetValue(ctx, nil)\n\t\t}\n\t\treturn\n\t}\n", mc.Field, mc.Field, mc.Field)
		fmt.Fprintf(b, "\tvar members []string\n")
		fmt.Fprintf(b, "\tfor _, mm := range vals {\n\t\tmembers = append(members, %s)\n\t}\n", mc.memberReadExpr())
		fmt.Fprintf(b, "\tm.%s = stringSetValue(ctx, members)\n}\n", mc.Field)
	}
}
